apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-deployment
spec:
  template:
    spec:
      containers:
        - name: app
          image: nginx
          securityContext:
            runAsUser: 0  # уязвимость: запуск контейнера от root
